### ISSUE TITLE
feature request: support the brand default color

### ISSUE THREAD

**Issue by Hilbert2048** [jlnrrg/simple_icons#102]
Icon(
              SimpleIcons.apple,
              color: Colors.red,
              size: iconSize,
            ),

--》 

 ColorSimpleIcon(SimpleIcons.apple)  directly return the brand icon with brand colors

the colors can be parsed from :

https://github.com/simple-icons/simple-icons/blob/develop/_data/simple-icons.json

or from the simple-icons.css in the simple-icons-font package

**Comment by jlnrrg** [comment]
I was busy with life so far, so sorry for only getting back now.
I will try to implement your proposal this week, as it seems quite beneficial.

**Comment by jlnrrg** [comment]
SimpleIconColors now holds the brand's color.
(Because of issues with the build tooling, not every brand was able to receive a color)
