### ISSUE TITLE
Remove unnecessary dependency on Material

### ISSUE THREAD

**Issue by n-bernat** [jlnrrg/simple_icons#107]
Currently, when adding this package to a project that doesn't use the Material Design there is a warning:

package:simple_icons has `uses-material-design: true` set but the primary pubspec contains `uses-material-design: false`. If the application needs material icons, then `uses-material-design`  must be set to true.

It has no other effects besides being annoying, but I would appreciate no unnecessary issues in my debug console.

Edit: Also, there is no reason to import the whole `package:flutter/material.dart` in `icon_data.dart` - `package:flutter/widgets.dart` is sufficient.

**Comment by jlnrrg** [comment]
Thank you for your issue.
I finally found some time today to work on this repository. So your issue should be resolved now, too.
(together with the auto update 🥳 )
