### ISSUE TITLE
No brand icons

### ISSUE THREAD

**Issue by giorgio79** [jlnrrg/simple_icons#13]
I was redirected here from https://github.com/NikSWE/flutter_brand_icons

I notice icons for brands are largely missing (tried Google, Apple) , so it does not seem to be a real replacement :)

**Comment by giorgio79** [comment]
Hmm when I search here https://simpleicons.org/?q=apple I can see the icon, but when the package does not seem to recognize it....

**Comment by jlnrrg** [comment]
when you say not recognize, what do you mean?
that you see nothing, or that the apple identifier is not available.
If possible a code example would be appreciated, bc. I just checked, and the apple icondata exists.

**Comment by giorgio79** [comment]
Thanks for the reply and please accept my apologies. I just double checked and the package indeed works! For some reason, autocomplete first pulled in SimpleLineIcons instead of SimpleIcons. It's all good and working fine!

**Comment by jlnrrg** [comment]
Apology accepted, but please double check in the future before filing a github issue as this costs time and effort on both ends.
Anyway, good to hear that there is no error and you also got it to work on your end. :smile:
