### ISSUE TITLE
Icons not displayed correctly in version 6.11.0

### ISSUE THREAD

**Issue by Mihai-B** [jlnrrg/simple_icons#61]
Hi,
simple_icons library worked very well for me. I am using version [6.1.0](https://pub.dev/packages/simple_icons/versions), and the next version to upgrade would be 6.11.0 as describe in the [pub.dev available versions](https://pub.dev/packages/simple_icons/versions)
However, when I update to version 6.11.0, all icons are mixed up.
Example of how it looks on version 6.1.0:
![v1](https://user-images.githubusercontent.com/1226719/156992807-ce19809c-1526-40e1-b404-17dba89b2ca5.png)

And this is how the icons look on version 6.11.0:
![iconsV11](https://user-images.githubusercontent.com/1226719/156992861-5dc00b44-0b1c-42bf-aa29-54034f485e90.png)

I tried cleaning the cache and everything but it doesnt work.

Does anyone else have the same problem with latest version?

**Comment by jlnrrg** [comment]
Thanks a lot for notifying me about this problem :smiley: 
I uploaded the version 6.13.0. Please confirm, that the issue is fixed for you.

**Comment by Mihai-B** [comment]
Hi,
Thank you for the quick reply. The issue seems to be fixed in `6.13.0 ` Thank you!
